### ISSUE TITLE
Applicationオブジェクトの設計方針

### ISSUE THREAD

**Issue by marihachi** [syuilo/Misskey.old#100]
- id
- name (32文字以下)
- userId
- createdAt
- consumerKey
- callbackUrl
- description
- developerName
- developerWebsite
- isSuspended

このissueでは、API application/create などからも利用される
Applicationオブジェクトの仕様を決めていきます

ご意見等あればお願いします

**Comment by marihachi** [comment]
このApplicationオブジェクトの中でapplication/createに使うパラメータについてですが
- name
- description
- developerName
- developerWebsite

が必要になってくるかなと思います
どうでしょうか

**Comment by syuilo** [comment]
それでいいと思う

**Comment by marihachi** [comment]
nameの文字数等の制約はどうしましょうか

**Comment by syuilo** [comment]
最大20文字くらい？

**Comment by marihachi** [comment]
32文字でどうでしょうか？
Misskey For Windows Desktop
って名前だと27文字もあるので

**Comment by syuilo** [comment]
じゃあそうしよう

**Comment by marihachi** [comment]
application/createをとりあえず通常の認証で実装しておきますね

**Comment by marihachi** [comment]
データベースのapplicationsテーブルのカラム名を開示してもらえないですか
他のテーブルについても可能だったらお願いします

**Comment by syuilo** [comment]
1   id
2   name
3   user_id
4   created_at
5   consumer_key
6   callback_url
7   description
8   developer_name
9   developer_website
10  is_suspended

**Comment by marihachi** [comment]
ありがとうございます

**Comment by marihachi** [comment]
Wikiにでもまとめた方が良いんじゃないでしょうか

**Comment by marihachi** [comment]
MisskeyWebのApplication.idってあるんですか？

**Comment by syuilo** [comment]
ある

**Comment by marihachi** [comment]
Application.name は「Web」ってことでおｋ？

**Comment by syuilo** [comment]
yes

**Comment by marihachi** [comment]
ok thx
