### ISSUE TITLE
アルバムシステム

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey.old#1017]
Misskeyへ投稿される画像を一元管理し再利用を可能にするために必要です。
- アルバムへの画像の登録は、直接アルバムにアップロードするか、投稿の際に画像が添付された場合に自動で登録される
- 画像を削除する際は、その画像を参照している投稿があるかどうかを確認し、あれば警告を表示するようにする
- 投稿に画像を添付する際は、新しくコンピューターから画像を選ぶか、アルバムの中から選ぶ
- アルバム内の画像は全て一意なIDを持つ
- そのIDを用いて画像にアクセスできるため、複数の投稿が一つの画像を参照するといった事も可能になる
- アルバム内の画像には、名前やタグを設定し管理する事ができる
- アルバム内の画像を自由に集めたアルバム(名称がかぶってややこしいので募集 とりあえずここでは便宜的にライブラリと呼ぶ事にする)を作る事ができ、そのライブラリごとに公開/非公開を設定できる 公開されたライブラリ内の画像は誰でも閲覧できる
- アルバム内に簡易的なフォルダを作れると便利かもしれない。が、必須では無い
- イメージ配信サーバーへ登録するパスも上記のIDのみに統一する

このシステムを実装するにあたっての問題は、すでにたくさんのコンテンツが投稿されているため、新たなアルバム・ベースの画像管理システムへの移行が多少面倒になる可能性があるということです。

特にイメージサーバー側は、OSのファイルシステム上に直にコンテンツを配置しているため、今からディレクトリ構造を変えるとなるとかなり面倒な気がします。ですので、今までに投稿されたコンテンツのパスはそのままに、アルバム内の画像はIDと実際に格納されているパスを保持するような設計にすると良さそうです。実装後は、パスはIDで統一すると言いましたので、IDとパスはぴったり一致する事になりますね。

…と思ったのですが、イメージサーバー側でパスについての多少の都合は少なからず存在するため、実装後もぴったり一致、ということは無いかもしれません。

まあとにかくIDで参照するとはいえ画像のIDと実際のパスの格納は分離しておくことに越したことはないので分離して格納するという設計は確実です。

---

まとめるとこの実装にあたってやるべきことはざっと思いつく限りでは以下の５つです。
- 画像モデルの策定・実装
- 既に投稿されている画像の移行(全ての画像を探し出し、それに対応する上記のモデルをセーブしていくといった形になるか)
- 画像モデルへの参照、画像モデルの挿入などの実装
- アルバムブラウザの実装
- 投稿の際にアルバム内から画像を選択する一連のフローの実装

実装の順番としては、やはり移行の状況などを確認できると作業がしやすいため、まず最初にモデルの作成、次にアルバムブラウザの実装、次に旧画像の移行、次に画像モデルの参照や登録処理、最後に投稿の際のフローの実装
といった感じでしょうか
## 画像モデル
- id (Misskeyで投稿される画像すべてを対象にした一意なID)
- user-id (画像作成者ID)
- name (ユーザーが自由につける名前)
- path (画像が実際に格納されているイメージサーバーのパス)
- tags (ユーザーが自由につける画像のタグ)
- created-at (画像登録日時)
- size (データ的な画像サイズ)
- width (画像の幅)
- height (画像の高さ)
- type (画像の種類)
- hash (画像のハッシュ値)
## アルバム内の画像を自由に集めたアルバムの名称案
- ライブラリ
- コレクション +1

**Comment by AyaMorisawa** [comment]
アルバム内の画像を自由に集めたアルバム → コレクション

**Comment by syuilo** [comment]
Goood!

**Comment by syuilo** [comment]
でもよく考えたら画像だけにそんなに特化する必要性もないように思えてきた
今までどおりひとつの投稿にはひとつ(または複数)の画像が付いている。おわり。っていう簡潔なスタンスの方が美しい気もしてきた

設計って難しい

**Comment by syuilo** [comment]
#1079 対策として、簡単なハッシュ値も保存しておくとよさそうだ

**Comment by AyaMorisawa** [comment]
ハッシュ値を保存しなくても投稿から画像のidを参照する形にすればid比較だけで良い

**Comment by syuilo** [comment]
投稿から画像のidを参照する形にはしますが、投稿の際に既存の画像を選択する方法に加えて新たな画像を添付できるようにもするので、その際はやはりハッシュ値などで判断するしかないです

**Comment by AyaMorisawa** [comment]
@syuilo ユーザーのアイコンもアルバムシステムで管理しますか？

**Comment by syuilo** [comment]
そうする予定です
