### ISSUE TITLE
Circleオブジェクトについて質問

### ISSUE THREAD

**Issue by ha-dai** [syuilo/Misskey.old#102]
Circleモデルのなかには
- createdAt: string;
- description: string;
- icon: string;
- id: number;
- name: string;
- screenName: string;
- userId: number;

がありますが、`icon:String`の中には何が入るのでしょうか。サークルのアイコンURLですか？

あと、`screenName`がサークル作成者のスクリーンネームだとしたら`userId`でこと足りませんか？

**Comment by ghost** [comment]
私もその２つを疑問に思っていました

**Comment by syuilo** [comment]
icon:String は廃止予定です。今まではアイコンが入っていました。
screenName: string はサークルのScreenNameです。

**Comment by ha-dai** [comment]
icon、了解しました。
サークルにもSNを設定するのですね。意外でしたが画期的だと思います。

**Comment by syuilo** [comment]
扱い的にはユーザーに近い
