### ISSUE TITLE
モバイル版の投稿詳細でアイコンをタップして行けるトーク画面のリンクが切れている

### ISSUE THREAD

**Issue by rinsuki** [syuilo/Misskey.old#1054]

**Comment by syuilo** [comment]
古いとは？

**Comment by rinsuki** [comment]
http://misskey.xyz/widget/talk/[screen name]の形式の物です

**Comment by syuilo** [comment]
それが 古い とはどういうことですか？

**Comment by rinsuki** [comment]
過去にこの形式のURLが使われていました(私の記憶によると)が、現在はそのURLの形式が使われていないからです

**Comment by syuilo** [comment]
では新しい形式とはどういうものですか？

**Comment by rinsuki** [comment]
http://misskey.xyz/[screen name]/talk
ですね

**Comment by syuilo** [comment]
http://misskey.xyz/[screen name]/talk
と
http://misskey.xyz/widget/talk/[screen name]
のものは全く別のものです。

**Comment by rinsuki** [comment]
あら、そうでしたか。

**Comment by AyaMorisawa** [comment]
@syuilo なぜバグ？

**Comment by syuilo** [comment]
@AyaMorisawa リンク切れは意図したものではないので
