### ISSUE TITLE
ログインできない件について

### ISSUE THREAD

**Issue by takeyari** [syuilo/Misskey.old#14]
刷新してからログインできません。ブラウザはSafariとFireFoxでやりましたがダメでした。JavaScriptの応答がないようです。対応をお願いします。

**Comment by syuilo** [comment]
@takeyari アカウント名を教えて頂いて宜しいでしょうか？

**Comment by takeyari** [comment]
@synです

**Comment by syuilo** [comment]
@takeyari ありがとうございます。
お使いのウェブブラウザに開発者ツールのようなものはございますでしょうか？

**Comment by takeyari** [comment]
はい

**Comment by syuilo** [comment]
@takeyari では、お手数ですがログイン画面を表示し、開発者ツールを表示してから、再度ログインをお試し頂けますでしょうか。
ログインを試したら画面はそのままにしておき、開発者ツールにネットワークを確認できるタブのようなものがあると思いますので、そこを開いてスクリーンショット等を撮影して私に確認させてください。
何卒ご協力をお願いいたします。

**Comment by takeyari** [comment]
ログイン画面から文字が打てなくなりました.............
http://i.imgur.com/A01GKlN.jpg

**Comment by takeyari** [comment]
ログインしてからのネットワークとエラーが出ていたのでそれも
http://i.imgur.com/LngCyEy.png
http://i.imgur.com/aF3BviE.png

**Comment by takeyari** [comment]
一応入れるようになりましたがロードに時間かかるしデザイン崩れるし投稿もできないです
http://i.imgur.com/tvhdO3e.jpg

**Comment by syuilo** [comment]
https://misskey.xyz/i/setting を開いて、ユーザーカラーを設定し直してみてください

**Comment by takeyari** [comment]
ユーザーカラーを変えてみましたがやはりダメです

**Comment by syuilo** [comment]
ごめんなさい、もう一回だけページをリロードしてもらえますか

**Comment by takeyari** [comment]
治りました!ありがとうございます!!!
