### ISSUE TITLE
API application/delete内でapp.destroy()を呼び出すか否か

### ISSUE THREAD

**Issue by marihachi** [syuilo/Misskey.old#142]
API talkMessage/deleteではisDeletedフラグを立てて見た目上の削除をしている様子でした
そこでapplication/deleteでもこのようにすべきなのか、またapp.destroy()を呼び出して削除すべきなのか という点で疑問を感じています

ご意見を頂けると嬉しいです

**Comment by syuilo** [comment]
app.destroy() しよう

**Comment by syuilo** [comment]
talkMessageはちょっと特別

**Comment by marihachi** [comment]
そなんだ 了解です
