### ISSUE TITLE
投稿、トーク メッセージ等のコンテントにMarkdownを使用できるようにするべきか否か

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey.old#18]
ご意見お待ちしております

**Comment by takeyari** [comment]
文章を装飾することにより意思伝達がやりやすくなるのでどちらでも採用すべき

**Comment by syuilo** [comment]
Markdownなら、Markdownに対応していないクライントから見ても全く意味が理解できなくなるということは起こらないからそこも利点
