### ISSUE TITLE
開発者センターの設計方針

### ISSUE THREAD

**Issue by marihachi** [syuilo/Misskey.old#26]
・アプリの設定ページ、APIリファレンスのページやその各APIページの切り替えはAjaxで
・APIリファレンスの各APIのソースに関しては /src/reference/apis/rest/下に
　layout.jadeをextendsしたJadeをテンプレートとして各API毎に作成
・APIリファレンスのページのソースは１つだけ用意
　GETのクエリ文字列によってテンプレートを呼び出し、表示を切り替え
・APIリファレンスのページのソースの場所は src/web/views/dev-reference.jade

※APIのパラメータや返り値等についての議論はここでは行いません

ご意見等お待ちしています

**Comment by takeyari** [comment]
DeveloperForum作りたいな

**Comment by syuilo** [comment]
@takeyari スレッドでいいんじゃね

**Comment by takeyari** [comment]
問題別にスレ分けたい感があるな

**Comment by takeyari** [comment]
タグつければいいか

**Comment by syuilo** [comment]
APIリファレンスのソースはそれぞれのAPI毎に分けたい
だから1ページで表示するようにしたいならそれらのソースをサーバー側で全部読み込んでから送り出すことになるね

**Comment by takeyari** [comment]
重そう

**Comment by marihachi** [comment]
じゃあAPI毎にページ作るようにするかあ

**Comment by syuilo** [comment]
重くはない

**Comment by marihachi** [comment]
とりあえず上記の方針を変更しておきました

**Comment by marihachi** [comment]
各APIリファレンスのソースを配置する場所として
・ src/web/views/ 下に dev/api/ 等のディレクトリを作って配置
・ src/web/views/ 下に「dev-api-user-show.jade」の様に通常通り配置
どちらが良いですかね

**Comment by syuilo** [comment]
ルート直下に配置します。ディレクトリ名は考え中

**Comment by syuilo** [comment]
APIリファレンスは、WebでもAPIでもModelでもないからね

**Comment by marihachi** [comment]
了解です

**Comment by marihachi** [comment]
それでも大丈夫だと思うね

**Comment by syuilo** [comment]
それぞれのドキュメントで統一した構造にしたいからJadeのテンプレートを活用しよう

**Comment by marihachi** [comment]
views/templates/ って事か

**Comment by syuilo** [comment]
/references/rest/template.jade
みたいな

**Comment by marihachi** [comment]
/references/rest/下に各APIのjadeを配置するっていう事?

**Comment by marihachi** [comment]
テンプレートの形式で

**Comment by syuilo** [comment]
そうだにゃ

**Comment by marihachi** [comment]
分かったにゃー

**Comment by syuilo** [comment]
んんんんん

**Comment by syuilo** [comment]
ディレクトリ構造迷うな
まあテンプレートの形式でリファレンスを記述することは決定なのでとりあえず書いていきましょう

**Comment by marihachi** [comment]
分かりました

**Comment by syuilo** [comment]
各APIの仕様について議論する必要があればそれぞれIssue建てましょう

**Comment by marihachi** [comment]
APIの処理の内容等についてはって事ですか

**Comment by syuilo** [comment]
それとかパラメータとか返り値とか

**Comment by marihachi** [comment]
了解です

**Comment by syuilo** [comment]
テンプレートは私が作っておく

**Comment by marihachi** [comment]
お願いします

**Comment by marihachi** [comment]
後から気づいたけどこれテンプレートじゃなくてレイアウトですね
https://github.com/syuilo/Misskey/blob/develop/reference/apis/rest/template.jade

**Comment by marihachi** [comment]
このtemplate.jade自体はレイアウトだよね？
これをextendしてblockの内容を記述したJadeファイルが「テンプレート」かなって思うんだけど

**Comment by syuilo** [comment]
そーなのかー

**Comment by marihachi** [comment]
そこでなんだけど、その各APIのテンプレートを直接res.displayに
渡しても良いかどうかについてなんですが どうですかね
テンプレートだからどこかにincludeで埋め込んでから返さないとダメですかね

**Comment by syuilo** [comment]
APIリファレンスページをひとつ作り、そこに対象のAPIのリファレンスを埋め込む

**Comment by marihachi** [comment]
それはどこのディレクトリに作りますか

**Comment by syuilo** [comment]
/src/web/views下かなぁ

**Comment by marihachi** [comment]
とりあえず/src/web/views/下でいきますか

**Comment by syuilo** [comment]
そうしよう
/src/web/views/ に dev ってディレクトリ作ってもいいかもしれない

**Comment by marihachi** [comment]
確かにその方が良いかも

**Comment by marihachi** [comment]
やっぱりdevディレクトリは作らないでいきます

**Comment by syuilo** [comment]
了解

**Comment by marihachi** [comment]
referenceディレクトリってsrcにも入れないん？

**Comment by syuilo** [comment]
もう何でもいいよ(白目)

**Comment by syuilo** [comment]
設計 is 難しい

**Comment by marihachi** [comment]
しゅいろたん is かわいい

**Comment by marihachi** [comment]
アプリケーション作成の際に使うAPIは通常のAPIと同じように実装しますか？
もし通常通りに実装するならエンドポイントをどうするかですね

**Comment by marihachi** [comment]
APIの呼び出しをMisskeyWeb経由のみ許可するとかは出来るんですかね？

**Comment by syuilo** [comment]
んーーーーーーーーーーーーーーーーーー

**Comment by marihachi** [comment]
んーーーーーーーーーーーーーーー

**Comment by syuilo** [comment]
トークンを使うとかそういう面倒な手を使わないと無理だ

**Comment by syuilo** [comment]
まあトークン用意したところでスクレイピングとかされたらどうしようもないんだが

**Comment by marihachi** [comment]
まあそれは防ぎようがないので考えない事にしましょう

**Comment by syuilo** [comment]
結論:ない

**Comment by syuilo** [comment]
そうしよう

**Comment by marihachi** [comment]
エンドポイントは
https://api.misskey.xyz/application/create
とかですかね

**Comment by syuilo** [comment]
yes

**Comment by marihachi** [comment]
了解ですん

**Comment by ghost** [comment]
application/create は公開しちゃうタイプですか？

**Comment by syuilo** [comment]
公開しない

**Comment by ghost** [comment]
わかりました

**Comment by marihachi** [comment]
ソースが公開されてる以上一般クライアントからは使えないようにする必要があると思いますね

**Comment by ghost** [comment]
そう思います

**Comment by syuilo** [comment]
通常の認証は用いない

**Comment by ha-dai** [comment]
とりあえず、FreeAccountからのリクエストについては、所持アプリ数等を比較し二個以上作らせないように という作業を内部でやればおk？

**Comment by syuilo** [comment]
yes

**Comment by syuilo** [comment]
脱線注意

**Comment by marihachi** [comment]
アプリケーション名の制約等はどうしますか

**Comment by marihachi** [comment]
その他のプロパティもそうですけど

**Comment by syuilo** [comment]
良ければ新しくIssue立ててみて
