### ISSUE TITLE
APIのHTTP/2対応

### ISSUE THREAD

**Issue by takeyari** [syuilo/Misskey.old#28]
2015年2月現在RFC化が進められているHTTP/2ですが、並列処理による速度向上が予想されUXの向上につながると思われます。(詳しくは、https://github.com/http2/http2-spec か http://summerwind.jp/docs/draft-ietf-httpbis-http2-16/ を御覧ください)
そこでHTTP/1.1仕様のMisskeyの各APIをHTTP/2準拠に移行していきたいと考えています。
意見お待ちしております。

**Comment by syuilo** [comment]
HTTP/1.1仕様ってどういうことだろ
ちなみに現在サーバーはSPDYに対応しています。サーバーのHTTP/2対応は準備中です。

**Comment by takeyari** [comment]
ウホ

**Comment by syuilo** [comment]
Node.jsのHTTP2モジュールがexpress上で動かない不具合が公式に確認されています。
この不具合が解決されるまで見合わせます。

**Comment by AyaMorisawa** [comment]
Node.jsのHTTP2モジュールがexpress上で動くようになればIssueを再オープンしてください。
