### ISSUE TITLE
サーバー側での画像のリサイズ

### ISSUE THREAD

**Issue by AyaMorisawa** [syuilo/Misskey.old#351]
特にアイコンを予め使うサイズにしておくと良い

**Comment by syuilo** [comment]
サイズ指定のURLはどうしましょうかね
基本: /img/icon/<username>

**Comment by syuilo** [comment]
表示されるデバイスのディスプレイ解像度が分からないから下手に設定できないな

**Comment by AyaMorisawa** [comment]
上限を決めておいてリサイズ後のサイズを指定するとか
