### ISSUE TITLE
なんか勝手に最初からフォローフォロワー存在するの気持ち悪いし死んでほしい以外の感情が沸かない

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey.old#354]
早速ご意見を頂きました。
やっぱりアカウント作成時にチュートリアルっぽいページを表示してそこで自由にフォローできるようにするとか

**Comment by Minkasy** [comment]
人それぞれだし、垢登録の一番最後に「管理者をフォローしますか？フォローするとタイムラインに投稿が表示されます。」みたいにしれっとオプションで付けてみるとか

**Comment by AyaMorisawa** [comment]
わざわざ管理者をフォローさせる必要ないし、フォローしたい人は勝手に探してフォローするのでは。

**Comment by syuilo** [comment]
最初にタイムラインに何か表示されていた方が親切

**Comment by syuilo** [comment]
別に管理者じゃなくていい

**Comment by AyaMorisawa** [comment]
ランダムに５人くらい表示させるのがよさそう

**Comment by ghost** [comment]
ユーザタグとかつくって、新規ユーザが自分のユーザタグを設定して、同じタグを持っているユーザをフォローしてみましょう！的にしたらいいと思います

**Comment by rinsuki** [comment]
TLになにも存在しない場合は誰かをフォローしてみましょうとかを出すとかどうでしょう

**Comment by Minkasy** [comment]
最初の利用の時には案内としてこ↑こ↓をどうのするとフォローできますみたいなので全ユーザ一覧みたいなのを作ってそっからフォローできるようにするとか(?)

**Comment by syuilo** [comment]
こ↑こ↓って？

**Comment by Minkasy** [comment]
あぁネタですので気にしないで
