### ISSUE TITLE
aboutでuser not found

### ISSUE THREAD

**Issue by hnakai0909** [syuilo/Misskey.old#355]
バグ再現方法:
左上Misskeyクリック->Aboutクリック->Sorry,user not found

原因:
Aboutのリンク先がmisskey.xyz/aboutである

対応策:
そもそもユーザーページのリンクがmisskey.xyz/ユーザー名 なので
例えばabout.misskey.xyzに飛ばす　など？

**Comment by syuilo** [comment]
Thanks for reporting.
URLはそれで合ってます。ルーティング&ページ作成してないだけです
