### ISSUE TITLE
Webにアクセスできない、不安定

### ISSUE THREAD

**Issue by takeyari** [syuilo/Misskey.old#37]
ソフト、ハードは前回の物と同じで症状も同じっぽいです

**Comment by syuilo** [comment]
ログイン出来ないではなくアクセス出来ないんですか？

**Comment by takeyari** [comment]
うーん
読み込まれて無いってかんじですかね。たまに入れるんですがスタイルが崩れてしまってアレです。

**Comment by syuilo** [comment]
クッキー削除しても変わりませんか？

**Comment by takeyari** [comment]
変わらないです

**Comment by syuilo** [comment]
ユーザーカラーに不正な値が設定されていたのが原因でした。
