### ISSUE TITLE
ログインページで点滅する

### ISSUE THREAD

**Issue by takeyari** [syuilo/Misskey.old#376]
ログインページでバグを発見しました。
どんなバグかは言葉で表しにくいのでキャプチャしました。https://youtu.be/wrR7G488ZBI
ブラウザはSafariです

**Comment by takeyari** [comment]
ミスりました。
ログインページでバグを発見しました。
どんなバグかは言葉で表しにくいのでキャプチャしました。https://youtu.be/wrR7G488ZBI
ブラウザはSafariです

**Comment by Minkasy** [comment]
Chromeで試したら出来なかったけどSafariだとなった。
Windows版の脆弱性ありありの古いバージョンのSafariでやったけど面白いことにユーザー名とパスワードとLoginが重なってログイン出来ない。
Chromeとかだと一番上が軸になって動くけどSafariだと真ん中が軸になるの初めて知った

**Comment by AyaMorisawa** [comment]
(Safari 7.1.2)

**Comment by ha-dai** [comment]
といいますか、パネルがゆらゆらするのはレンダリングの際に文字がぼやけますし(少なくとも自環境では)、ユーザビリティが悪いので動かさない(ゆらゆらさせない)ほうがいいと思います。

**Comment by AyaMorisawa** [comment]
:+1: @ha-dai

**Comment by Minkasy** [comment]
ゆらゆらするのは自環境では最初重くなるだけだし基本トラブルはないからゆらゆらさせないのではなくある程度ゆらゆらさせて割とすぐ静止させる程度がいいかな、と。

**Comment by ha-dai** [comment]
@mintyan 上からパラっとめくれる感じはいいと思いますが、その後いつまで揺れてんねん ってことですね。

**Comment by Minkasy** [comment]
@ha-dai うみゅ
こ～れずっと揺れてるやつだわｗと思って放置してたら止まってたしそれに気づいていつまで揺れてるのか見てたら長すぎだろうがｗって突っ込みたくなったし(?)

**Comment by syuilo** [comment]
最初重くなる…？

**Comment by syuilo** [comment]
ぼやけるって言ってもアンチエイリアス程度だから気になるほどではないな

**Comment by AyaMorisawa** [comment]
最初重くなるのは背景画像のせいかと

**Comment by syuilo** [comment]
yes

**Comment by AyaMorisawa** [comment]
重くなることについては #384

**Comment by syuilo** [comment]
デザインが刷新されました。
