### ISSUE TITLE
New3DSとPSVitaでアカウント作成時にユーザーカラーを指定できない

### ISSUE THREAD

**Issue by rinsuki** [syuilo/Misskey.old#381]
また、ソフトウェアキーボードの確定(など)を押しても作成していますのまま15分以上動かない。

**Comment by syuilo** [comment]
Thakns for reporting.
一部の端末とは

**Comment by rinsuki** [comment]
私の端末なのでNew3DSとPSVita(UAからしてWebkitベース)です

**Comment by Petitsurume** [comment]
私の端末なのでNew3DSとPSVita(UAからしてWebkitベース)です

**Comment by Petitsurume** [comment]
私の端末なのでNew3DSとPSVita(UAからしてWebkitベース)です

**Comment by syuilo** [comment]
モバイルにはまだ未対応です。
