### ISSUE TITLE
APIレートリミットをどのように実装すべきか

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey.old#44]

**Comment by marihachi** [comment]
model上でAPIリミットを実装するのはどうですか
MisskeyWebにもAPIにも反映されますし

**Comment by syuilo** [comment]
どうやってリミットを実装する？

**Comment by marihachi** [comment]
IPアドレスとuser.idとかを元に以前のリクエストとの間隔を測って
リクエストを処理するかを判断するとか

**Comment by syuilo** [comment]
んんーーーー
ちなみに判断するならAccessTokenでだな

**Comment by syuilo** [comment]
私的には1時間x回みたいな感じで制限したい

**Comment by syuilo** [comment]
それをどうやって実装するか

**Comment by marihachi** [comment]
むずかしいなあ

**Comment by marihachi** [comment]
アクセストークンごとに１時間前までのログを残しておかなくてはいけないって事だよなあ

**Comment by syuilo** [comment]
そんな感じになるのかねぇ

**Comment by marihachi** [comment]
じゃないと今から1時間以内に何回アクセスがあったかなんて分からないでしょ

**Comment by marihachi** [comment]
((多分))

**Comment by syuilo** [comment]
ミス AccessToken毎じゃなくてユーザー毎だった

**Comment by marihachi** [comment]
言われてみればそうだｗ

**Comment by syuilo** [comment]
それだとアプリ変えれば回避できちゃうからね

**Comment by marihachi** [comment]
だね

**Comment by marihachi** [comment]
DBにuser.idとアクセス日時を保存して
1時間の間で何件ヒットするかで判断するとか

**Comment by marihachi** [comment]
ファイルのロックを一定期間するっていう制限の方法もあるみたいだけど
Node.jsはロックが出来ないはずだからと思って

**Comment by syuilo** [comment]
なんのファイルだろ
