### ISSUE TITLE
自作テーマの設計方針について

### ISSUE THREAD

**Issue by marihachi** [syuilo/Misskey.old#47]
**現行の方針**
・開発者センターから自作テーマの投稿を可能に
・非公開状態で投稿され、公開をするかどうかの設定を出来るのはPlusAccountのみ
・公開設定に従って検索にヒットさせるかを決定
・使用するテーマの設定は rooting: /i/setting から (自作のテーマは常にページに表示)
・テーマの検索が出来るようにユーザーテーマセンター的なページを作る
**不明点**
・今のところ無し

ご意見等ありましたらお願いします

**Comment by syuilo** [comment]
テーマ専用のページを作る
そこでテーマの検索を行えるようにするとか

**Comment by syuilo** [comment]
Googleみたいにテーマを公開するにはPlusAccountな必要があるようにしようかなぁ
