### ISSUE TITLE
PlusAccountの仕様

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey.old#49]
PremiumAccountの正式名称がPlusAccountに決定しました。
PlusAccountの特典を検討します。
- 投稿する画像の画質が通常より高くなる
- 自作のテーマを公開できる
- アプリケーションを無制限に作成できる(通常のアカウントは1個まで)

アップグレードについて
\1,000
支払い方法: 今のところアマギフ/Vプリカ/銀行振込 に対応

**Comment by ghost** [comment]
PlusAccountではありませんが、今までのアプリケーションが1つ以上あります。
それはどうなりますか？

**Comment by syuilo** [comment]
引き続き使用できます。

**Comment by ghost** [comment]
もうアプリケーションをつくったのでもう作れませんか？
それとアプリケーションの名前などは変更できますか？

**Comment by syuilo** [comment]
新しくアプリケーションを作成するにはアカウントのアップグレードが必要です。
アプリケーション名の変更については未定です。

**Comment by takeyari** [comment]
アカウントのアップグレードについて具体的にまとめせんか?
(金額や支払い方法など。多すぎると混乱するしトラブルのもとにもなるので)

**Comment by ghost** [comment]
いいですね

**Comment by marihachi** [comment]
作成できるアプリの数は2個ぐらいはあった方が良いのでは

**Comment by marihachi** [comment]
テーマの作成も1つは出来た方が良いかなと
テーマを作成した事が無いと、アップグレードして扱えるかどうかへの不安が生まれると思います

**Comment by syuilo** [comment]
私はテーマを公開したくてGoogleに課金した経験があるから結構いいと思ったんだけどなぁ

**Comment by ha-dai** [comment]
テーマは無料で自分に限りプレビューができるとかどうですか？パブリッシュ(公開)が有料っていう。

**Comment by ghost** [comment]
いいですね

**Comment by syuilo** [comment]
@ha-dai そうするつもりだよー

**Comment by syuilo** [comment]
繰り返しますがGoogleと同じで、公開がPlusAccountでないと出来ないのであって、自分で使用するぶんには通常のアカウントでも出来ます。

**Comment by marihachi** [comment]
なるほど それならいいと思います
