### ISSUE TITLE
どうやって収入を得るか

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey.old#50]
まずはじめに、Misskeyの運営にはサーバー等のコストがかかることをご理解ください。
ですので、何かしらの方法で収入を得る必要があります。収入がないと、Misskeyを運営することが出来ません。

PlusAccountの仕様に意見があったので、じゃあ他にどういう収入源を作るかということについて検討します。
ユーザーが増えれば広告収入も視野に入ってきますけれども、増えるまでの間は他の方法を考える必要があります。

**Comment by takeyari** [comment]
PlusAccountにもっとお金払いたくなる機能などをつけることはどうでしょうか?

**Comment by Minkasy** [comment]
何かデザインとか機能とかを付け加えられる状態にして、それをポイントでGetするようにし、そのポイントはいろいろ投稿などしているうちに溜まっていくけれど、お金を払うことでお金をポイントに換算できるというのはどうでしょうか。
それなら頑張ってればたまりますし、不平等なんてことも殆どないかなぁ、と思います。
takeyari氏の提案もこの機能にすることも出来ますし、いいと思います。

**Comment by takeyari** [comment]
何より「課金しないとできない」というプレミアをつけないと誰も金なんか払ってくれない

**Comment by syuilo** [comment]
だから私は「アプリの複数作成」「テーマの公開」がいいと思ったんだけど

**Comment by Minkasy** [comment]
> 何より「課金しないとできない」というプレミアをつけないと誰も金なんか払ってくれない

なるほど

**Comment by takeyari** [comment]
あとほんの思いつきなのですが、ユーザーもお金を取れるというのはどうでしょか?
例えば、「ユーザーが物を売る→売れる→ユーザーにお金が入る→Misskeyにもいくらかの手数料→どっちも儲かる」
というWin-Winを実現をすることでユーザーが増えたり、収入を得ることができるのではないでしょうか。

**Comment by syuilo** [comment]
金をユーザー間でやりとりするシステムを実装するにはMisskey自体が不安定過ぎて危険

**Comment by Minkasy** [comment]
> 金をユーザー間でやりとりするシステムを実装するにはMisskey自体が不安定過ぎて危険

やばそう
案、自分はあんまり思いつかないし、一番現実的なのはやっぱり「アプリの複数作成」「テーマの公開」ここら辺なのかなぁ?とは思う
