### ISSUE TITLE
post/show等から返されるPostオブジェクトの仕様

### ISSUE THREAD

**Issue by marihachi** [syuilo/Misskey.old#57]
- **id** :ID
- **text** :本文
- **createdAt** :投稿日時
- **userId** :ユーザーID
- **favoritesCount** :被ふぁぼ
- **repostsCount** :被RP
- **isImageAttached** :画像が添付されているか
- **inReplyToPostId** :返信先ステータスID
- **user** :投稿したユーザーのユーザーオブジェクト(付加しない事も可)
- **app** :投稿に経由したアプリケーションのアプリケーションオブジェクト

APIリファレンスページでPostオブジェクトについてを記述するに当って、
どういったパラメータを含めるかを決定していきたいなと思います

ご意見お願いします

**Comment by syuilo** [comment]
ｲｼｭﾀｲはtypoかな？

**Comment by marihachi** [comment]
Postだったｗ

**Comment by syuilo** [comment]
いまのところModelには

```
    appId: number;
    createdAt: string;
    favoritesCount: number;
    id: number;
    inReplyToPostId: number;
    isImageAttached: boolean;
    repostsCount: number;
    repostFromPostId: number;
    text: string;
    userId: number;
```

があるな

**Comment by marihachi** [comment]
favoritesCountってストリーミングだったらイベントとかで送られてきたりするのかな

**Comment by marihachi** [comment]
favoritesCountはまあ含めても良さそうだけど

**Comment by syuilo** [comment]
確かにpost/createで返るのは絶対0だな

**Comment by marihachi** [comment]
でもオブジェクトで渡す以上統一した方がよくない？
((そもそもオブジェクトが返るって考え始めたのは私だけど))

**Comment by syuilo** [comment]
うむ

**Comment by marihachi** [comment]
TwitterではPostオブジェクト上にUserオブジェクトも含まれてるって感じだったよね
その辺りはどうする

**Comment by syuilo** [comment]
基本含めるけどオプションで含めないようにも出来るようにする

**Comment by marihachi** [comment]
Userを丸々入れちゃう？

**Comment by syuilo** [comment]
うん

**Comment by marihachi** [comment]
OK

**Comment by syuilo** [comment]
ブラウザの開発者ツール見てみると分かるよ
ステータス投稿した時とか

**Comment by syuilo** [comment]
postの中にuserが入ってる

**Comment by marihachi** [comment]
まじか

**Comment by marihachi** [comment]
appオブジェクトについてはどうしますか

**Comment by syuilo** [comment]
appも含めるかぁ

**Comment by syuilo** [comment]
postオブジェクトのリファレンスは誰が書きます？

**Comment by marihachi** [comment]
viaは表示する場合がほとんどでしょうから有った方が良さそうですかね

**Comment by marihachi** [comment]
私が書きます

**Comment by syuilo** [comment]
okaythx

**Comment by marihachi** [comment]
isReplyはinReplyToPostIdをチェックすれば分かるので要らないかなと思うんですが
どうでしょう

**Comment by syuilo** [comment]
要らないかな

**Comment by marihachi** [comment]
どうします？

**Comment by syuilo** [comment]
互換性のためだけに残しておこう

**Comment by marihachi** [comment]
そうですね
