### ISSUE TITLE
ホームが読み込めない

### ISSUE THREAD

**Issue by sirotama** [syuilo/Misskey.old#634]
/i/mentionが読めこめないという話題が出ていたがそのうちホームすら読み込めなったようだ　自分の知る限りではイメージサーバーを分けるメンテの前まではmentionを利用できていた。

「リロードしたら利用できなくなる」と釘を刺されたが好奇心からリロードしたら詰んだ。

**Comment by syuilo** [comment]
現時点で原因が全くわかっていません。

**Comment by syuilo** [comment]
一時的な解決策としては、ユーザーエージェントをiPhone等のモバイル端末に設定しモバイルサイトを利用することです。
