### ISSUE TITLE
iPhoneからタイムラインに画像投稿するとひっくり返る

### ISSUE THREAD

**Issue by takeyari** [syuilo/Misskey.old#706]
iPhoneから画像投稿するとひっくり返る現象が起きています。
他の個体で実験はしていないのでよくわかりませんが修正できたらよろしくおねがいします。

**Comment by syuilo** [comment]
ひっくり返って表示されるかどうかは、ブラウザによるようです。

**Comment by syuilo** [comment]
しかしどのブラウザも、画像のみを表示した場合は正しい向きで表示されるという点が共通しています。

**Comment by rinsuki** [comment]
画像の傾き情報(縦向きに撮られたか、横向きに撮られたか)を考慮してるかどうかなんでは

**Comment by syuilo** [comment]
はい。

**Comment by rinsuki** [comment]
それなら、画像の回転情報に合わせてMisskey側で回転させて、回転情報を消せばどのブラウザでも同じ表示が期待できるのでは
サーバー側の処理は多少増えますが
