### ISSUE TITLE
POST status/update でサーバーエラーが発生する

### ISSUE THREAD

**Issue by marihachi** [syuilo/Misskey.old#768]
textパラメータを付加してリクエストするとエラーが発生して登校できません。
C#のプログラムで発生しました
![j4k](https://cloud.githubusercontent.com/assets/10358431/9325717/6613e770-45cf-11e5-9985-749ce58641e6.png)

**Comment by marihachi** [comment]
こっちのプログラムミスの可能性がある
保留で

**Comment by syuilo** [comment]
ok

**Comment by syuilo** [comment]
まあでも適切なエラーメッセージを返せてない時点でこちら側の問題でもある
