### ISSUE TITLE
@github/うんぬんでhttps://github.com/syuilo/Misskey/うんぬんに飛ぶようになったら便利ではないか

### ISSUE THREAD

**Issue by rinsuki** [syuilo/Misskey.old#782]
わざわざhttpsから書くのもなんだかなぁという気がするので

**Comment by AyaMorisawa** [comment]
URLを直接タイピングするというケースは少ないのでは？

**Comment by ha-dai** [comment]
逆に書くのがだるいので自分なんかは既に#から書き始めています

**Comment by AyaMorisawa** [comment]
外部サービスのURLを短縮して書くための統一した書式があると便利かも

**Comment by ha-dai** [comment]
3文字idは実在しない予定なので、`@git/123`で＃123にリダイレクトするようにしてみてはいかがですか？

**Comment by syuilo** [comment]
3文字idは実在しない予定ではない

**Comment by rinsuki** [comment]
では、@の後にスクリーンネームで使えないような文字を入力するなどはどうでしょう(*や+とか)
(上のコメント、スクリーンネームがPlus-Accountになると変えられるようになったりするのだろうか)
