### ISSUE TITLE
account/update-iconをリクエストするとタイムアウトする

### ISSUE THREAD

**Issue by rinsuki** [syuilo/Misskey.old#798]

**Comment by syuilo** [comment]
PUTでリクエストしていますか？

**Comment by rinsuki** [comment]
はい。
ためしにリクエスト先をhttp://httpbin.org/put に変更してみたところ、正常にアップロードされていました。

**Comment by Petitsurume** [comment]
はい。
ためしにリクエスト先をhttp://httpbin.org/putに変更してみたところ、正常にアップロードされていました。

**Comment by rinsuki** [comment]
こちらがわの間違いでした
ご迷惑をお掛けして申し訳ありませんでした

**Comment by AyaMorisawa** [comment]
@Petitsurume もしよければどのような間違いだったか教えてくださいませんか？

**Comment by rinsuki** [comment]
@AyaMorisawa こちら側(PHP)でライブラリに直でCURLFile渡していて、それが文字列になってリクエストされていたようです
Githubの(ライブラリー側のリポジトリの)issuesにて正しい情報を知ることができました
