### ISSUE TITLE
モバイル版のメニュー「アカウント」は重複しているのでは？

### ISSUE THREAD

**Issue by ha-dai** [syuilo/Misskey.old#802]
先頭項目の`アイコン＋名前`部をタップすれば、自分のユーザページに飛べるので、`アカウント`という項目を用意することは、ナビゲーション重複ではないだろうか。

**Comment by syuilo** [comment]
デザイン的に現在の状態が良いです。

**Comment by ha-dai** [comment]
Androidアプリのガイドラインと比較して違和感があっただけなので、重要な問題ではないです。
