### ISSUE TITLE
検索結果でハイライトされたスクリーンネームのリンクがおかしい

### ISSUE THREAD

**Issue by sirotama** [syuilo/Misskey.old#819]
Example: See https://misskey.xyz/search?q=srtm and click the screen name `@srtm`.

Expected: `https://misskey.xyz/srtm`

Got: `https://misskey.xyz/%3Cmark%3Esrtm%3C/mark%3E`

**Comment by sirotama** [comment]
updated text because github sucks :(

**Comment by AyaMorisawa** [comment]
@sirotama Updated your comment

**Comment by sirotama** [comment]
@AyaMorisawa :+1:

**Comment by stephenmcghee** [comment]
?

**Comment by AyaMorisawa** [comment]
@srtm Sorry. You are not related this issue.
