### ISSUE TITLE
Googlebotが開発チャンネルにアクセスしたら安定チャンネルにリダイレクト

### ISSUE THREAD

**Issue by rinsuki** [syuilo/Misskey.old#871]

**Comment by syuilo** [comment]
どういうことですか？

**Comment by syuilo** [comment]
まず何の検索結果だろう

**Comment by rinsuki** [comment]
https://www.google.co.jp/search?q=あぁ^～こころがぴょんやんするんじゃあ^～
のまんなかよりちょっと上くらいのところ

**Comment by marihachi** [comment]
わしだ

**Comment by ha-dai** [comment]
1206にアクセスした場合、`<meta name=”robots” content=”noindex” />`するのはいかがですか？

**Comment by syuilo** [comment]
インデックスさせないよりも、安定版にリダイレクトさせた方が良い

**Comment by rinsuki** [comment]
その場合、UAで判断という形になりますかね

**Comment by syuilo** [comment]
そうですね

**Comment by Petitsurume** [comment]
その場合、UAで判断という形になりますかね
